const data = {
  products: [
    {
      _id: '1',
      name: 'iPhone 14 Pro Max',
      category: 'Smartphones',
      image: '/images/p3.jpg',
      price: 201990,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      _id: '2',
      name: 'iPhone 14 Pro',
      category: 'Smartphones',
      image: '/images/p3.jpg',
      price: 201990,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      _id: '3',
      name: 'iPhone 14',
      category: 'Smartphones',
      image: '/images/p3.jpg',
      price: 201990,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      _id: '4',
      name: 'iPhone 13 Pro Max',
      category: 'Smartphones',
      image: '/images/p3.jpg',
      price: 201990,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      _id: '5',
      name: 'iPhone 14 Pro',
      category: 'Smartphones',
      image: '/images/p3.jpg',
      price: 201990,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Product',
    },
  ],
};

export default data;
